org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.172

mod_id=markiplier_overlay_port
mod_name=Markiplier Overlay Port
mod_version=1.0.0-alpha.2
mod_group_id=com.korikosmos.markiplieroverlayport
mod_authors=KoriKosmos
mod_description=NeoForge 1.21.1 port bootstrap for the Markiplier overlay mod.
